### ISSUE TITLE
Improve the gas cost for users at sale time

### ISSUE THREAD

**Issue by RareSkills** [RareSkills/RSA-presale-allowlist#8]
IMPORTANT. This issue focuses on gas cost for the execution of the user, as measured here:

https://github.com/RareSkills/RSA-presale-allowlist/blob/main/test/rsa.test.js#L182

Although we welcome suggestions to improve the other gas costs, this is the one relevant to the gitcoin bounty.

"Clever but sketchy" gas optimizations don't qualify. This is intended to be used for production. You may not introduce security or reliability vulnerabilities. Restructuring the code to accomplish the same thing in a better way is acceptable. You are not required to follow the current structure of the code.

Bounty sponsored by [RareSkills](https://www.rareskills.io)

**Comment by nightwolf3** [comment]
@RareSkills Hello
when is the deadline because Im confused as to why we can't apply until 3 days before it?

**Comment by enehizy** [comment]
> @RareSkills Hello when is the deadline because Im confused as to why we can't apply until 3 days before it?

please answer

**Comment by RareSkills** [comment]
The requirements will be posted on Twitter

**Comment by SurroundingArt64** [comment]
Is this bounty closed?

**Comment by RareSkills** [comment]
Please see the terms in the description

**Comment by abebeos** [comment]
> The requirements will be posted on Twitter

Really messy this bounty. Twitter for requirements?

**Comment by RareSkills** [comment]
This is a Twitter contest. The bounty is the award.
